# Generated by Django 4.2 on 2023-12-16 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0003_task_is_done_task_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('reminder_type', models.PositiveSmallIntegerField(choices=[(1, 'email'), (2, 'sms')], default=None)),
                ('time_left', models.TimeField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reminder', to='task.task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
