# Generated by Django 4.2 on 2024-07-03 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0006_task_reminder_time'),
        ('reminder', '0004_remove_reminder_time_left_reminder_reminder_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='reminder_time',
        ),
        migrations.AddField(
            model_name='reminder',
            name='time_left',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reminder',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reminder', to='task.task'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reminder', to=settings.AUTH_USER_MODEL),
        ),
    ]
