# Generated by Django 4.2 on 2024-07-03 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_reminder_time_alter_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='reminder_time',
        ),
    ]
